import random

NUM_PLAYERS = 2
USER_POSITION = random.randrange(NUM_PLAYERS)
NUM_DECKS = 1
RESHUFFLE_RATIO = .5

PLAYER_SETTINGS = [[0, 'bot']] * NUM_PLAYERS
REAL_USER_BASE = [100, 'Player', True]
PLAYER_SETTINGS[USER_POSITION - 1] = REAL_USER_BASE
